name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      - name: Create virtual environment
        run: |
          python -m venv venv
          .\venv\Scripts\activate

      - name: Install dependencies
        run: |
          .\venv\Scripts\activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          .\venv\Scripts\activate
          python -m unittest discover -s tests